In [136]:
import pandas as pd
import os
import sys
import warnings

warnings.filterwarnings('ignore')

project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.insert(0, project_root)

from app.services import ModelsManagement
from app.utils import ml_utils

from app.services.models_management import train_brindges_structures_model
from app.utils.ml_utils import get_bridges_structures_tunnels


%load_ext autoreload
%autoreload 2
%reload_ext autoreload


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [138]:
fase='II'
mm_fase_II = ModelsManagement(fase)
df_vp_fase_II = mm_fase_II.prepare_data()

fase='III'
mm_fase_III = ModelsManagement(fase)
df_vp_fase_III = mm_fase_III.prepare_data()


In [ ]:
# FASE II
results_fase_II, summary_df_fase_II = mm_fase_II.train_models()
summary_df_fase_II

In [ ]:
target_suelos = '4 - SUELOS'
df_clean = df_vp_fase_III[(df_vp_fase_III[target_suelos] > 0) & (((df_vp_fase_III['PUENTES VEHICULARES UND'] > 0) &
                                                                  (df_vp_fase_III['PUENTES VEHICULARES M2'] > 0)) | (df_vp_fase_III['PUENTES PEATONALES UND'] > 0))]

df_grouped = get_bridges_structures_tunnels(df_clean, target_suelos)
df_grouped

CÓDIGO          ALCANCE    4 - SUELOS  LONGITUD KM  \
0     0001  Segunda calzada  1.878437e+08       17.400   
1  0266702     Mejoramiento  1.326106e+07        5.000   
2  0300605  Segunda calzada  1.308015e+08       17.000   
3  0347801   Rehabilitación  5.740222e+08       16.850   
4  0552903     Mejoramiento  6.696069e+07       10.060   
5  0581301     Mejoramiento  4.285348e+07        5.243   
6  0654801            Nuevo  1.470113e+08       69.310   
7     6935  Segunda calzada  1.029912e+08       37.960   

   PUENTES VEHICULARES UND  PUENTES VEHICULARES M2  PUENTES PEATONALES UND  \
0                       11                    4856                      14   
1                        0                       0                       1   
2                       13                   16654                       0   
3                       26                   51069                       0   
4                        6                    3837                       0   
5                        2                      38                       0   
6                        7                       0                      10   
7                        4                    6292                       1   

   PUENTES PEATONALES M2  TUNELES UND  TUNELES KM  
0                   1365            0      0.0000  
1                     58            0      0.0000  
2                      0            0      0.0000  
3                      0           20      3.1947  
4                      0            0      0.0000  
5                      0            3      0.1460  
6                      0            1      0.0000  
7                     77            0      0.0000

In [131]:
predictors_suelos = ['PUENTES VEHICULARES UND', 'PUENTES VEHICULARES M2']
df_clean = ml_utils.remove_outliers(df_grouped, target_suelos)
ml_utils.train_multiple_models(df_clean, predictors_suelos, target_suelos, log_transform='both')
# train_brindges_structures_model(df_grouped, target_suelos, predictors_suelos, use_log_transform=True)

(array([[ 2.48490665,  8.48817624],
        [ 0.        ,  0.        ],
        [ 2.63905733,  9.72046575],
        [ 3.29583687, 10.84095252],
        [ 1.94591015,  8.25270668],
        [ 1.09861229,  3.66356165],
        [ 2.07944154,  0.        ],
        [ 1.60943791,  8.74719318]]),
 array([1.87843738e+08, 1.32610640e+07, 1.30801475e+08, 5.74022243e+08,
        6.69606925e+07, 4.28534818e+07, 1.47011320e+08, 1.02991160e+08]),
 array([1.76116199e+08, 1.41991054e+07, 2.34803427e+08, 3.36425760e+08,
        1.08196810e+08, 4.27960570e+07, 8.40274363e+07, 5.64600722e+07]),
 TransformedTargetRegressor(func=<ufunc 'log1p'>, inverse_func=<ufunc 'expm1'>,
                            regressor=Pipeline(steps=[('scaler',
                                                       StandardScaler()),
                                                      ('model',
                                                       Ridge(alpha=0.1))])),
 {'Model': 'Ridge',
  'R²': 0.659,
  'MAE': 63134066.208,


In [140]:
results_fase_III, summary_df_fase_III = mm_fase_III.train_models()
summary_df_fase_III

Target                    Alcance  \
0        2.1 - INFORMACIÓN GEOGRÁFICA            Segunda calzada   
1        2.1 - INFORMACIÓN GEOGRÁFICA  operacion y mantenimiento   
2        2.1 - INFORMACIÓN GEOGRÁFICA             Rehabilitación   
3   2.2 - TRAZADO Y DISEÑO GEOMÉTRICO            Segunda calzada   
4   2.2 - TRAZADO Y DISEÑO GEOMÉTRICO  operacion y mantenimiento   
5   2.2 - TRAZADO Y DISEÑO GEOMÉTRICO               Mejoramiento   
6   2.2 - TRAZADO Y DISEÑO GEOMÉTRICO             Rehabilitación   
7   2.2 - TRAZADO Y DISEÑO GEOMÉTRICO             Puesta a punto   
8                2.3 - SEGURIDAD VIAL            Segunda calzada   
9                2.3 - SEGURIDAD VIAL  operacion y mantenimiento   
10               2.3 - SEGURIDAD VIAL               Mejoramiento   
11               2.3 - SEGURIDAD VIAL             Rehabilitación   
12               2.3 - SEGURIDAD VIAL             Puesta a punto   
13        2.4 - SISTEMAS INTELIGENTES            Segunda calzada   
14        2.4 - SISTEMAS INTELIGENTES  operacion y mantenimiento   
15        2.4 - SISTEMAS INTELIGENTES               Mejoramiento   
16        2.4 - SISTEMAS INTELIGENTES             Puesta a punto   
17                        5 - TALUDES            Segunda calzada   
18                        5 - TALUDES               Mejoramiento   
19                        5 - TALUDES             Rehabilitación   
20                        5 - TALUDES             Puesta a punto   
21                      6 - PAVIMENTO            Segunda calzada   
22                      6 - PAVIMENTO             Rehabilitación   
23                      6 - PAVIMENTO               Mejoramiento   
24                      6 - PAVIMENTO             Puesta a punto   
25                     7 - SOCAVACIÓN            Segunda calzada   
26                     7 - SOCAVACIÓN  operacion y mantenimiento   
27                     7 - SOCAVACIÓN               Mejoramiento   
28                     7 - SOCAVACIÓN             Rehabilitación   
29                     7 - SOCAVACIÓN             Puesta a punto   
30                       11 - PREDIAL             Rehabilitación   
31       15 - OTROS - MANEJO DE REDES            Segunda calzada   
32       15 - OTROS - MANEJO DE REDES  operacion y mantenimiento   
33       15 - OTROS - MANEJO DE REDES             Puesta a punto   
34      16 - DIRECCIÓN Y COORDINACIÓN                    General   
35                       3 - GEOLOGÍA                    General   
36                         4 - SUELOS                    General   
37                    8 - ESTRUCTURAS                    General   
38                        9 - TÚNELES                    General   
39        10 - URBANISMO Y PAISAJISMO                    General   
40                    13 - CANTIDADES                    General   

                Model     R²           MAE          RMSE  MAPE (%)  n_samples  \
0          ElasticNet  1.000  4.525410e+02  4.795720e+02     0.033          4   
1          ElasticNet  1.000  3.358601e+03  3.565073e+03     0.163          3   
2          ElasticNet  1.000  6.105030e+02  7.056370e+02     0.002          3   
3                 SVR  0.492  9.999063e+05  1.874178e+06    29.641         16   
4          ElasticNet  1.000  1.542748e+04  1.637573e+04     0.163          3   
5               Ridge  0.338  4.954865e+06  9.490122e+06    36.907         10   
6          ElasticNet  1.000  1.599611e+05  1.849783e+05     1.210          5   
7          ElasticNet  1.000  1.080983e+04  1.358786e+04     0.169          8   
8    Gaussian Process  0.864  8.529342e+05  1.734885e+06    25.556         17   
9          ElasticNet  1.000  4.083710e+03  4.334749e+03     0.163          3   
10         ElasticNet  0.086  4.051322e+06  7.027524e+06    55.761         10   
11   Gaussian Process  0.900  1.427764e+06  3.036611e+06     4.501          5   
12         ElasticNet  1.000  1.162009e+04  1.460636e+04     0.169          8   
13     Bayesian Ridge  0.804  8.510775e+

In [141]:
predictions = mm_fase_III.predict_fase_III(
    codigo='',
    longitud_km=8.35,
    puentes_vehiculares_und=10,
    puentes_vehiculares_m2=24258.85,
    puentes_peatonales_und=0,
    puentes_peatonales_m2=0,
    tuneles_und=5,
    tuneles_km=0.92,
    alcance='Rehabilitación',
    models=results_fase_III
)
predictions

{'1 - TRANSPORTE': None,
 '2.1 - INFORMACIÓN GEOGRÁFICA': np.float64(51664955.090292536),
 '2.2 - TRAZADO Y DISEÑO GEOMÉTRICO': np.float64(32610213.543953456),
 '2.3 - SEGURIDAD VIAL': np.float64(25349383.224667624),
 '2.4 - SISTEMAS INTELIGENTES': None,
 '5 - TALUDES': np.float64(96969727.35904229),
 '6 - PAVIMENTO': np.float64(68245555.54244071),
 '7 - SOCAVACIÓN': np.float64(85607785.18018383),
 '11 - PREDIAL': np.float64(22463525.582107335),
 '12 - IMPACTO AMBIENTAL': None,
 '15 - OTROS - MANEJO DE REDES': None,
 '16 - DIRECCIÓN Y COORDINACIÓN': np.float64(262599320.02182275),
 '3 - GEOLOGÍA': np.float64(44833760.29626786),
 '4 - SUELOS': np.float64(185219851.8095359),
 '8 - ESTRUCTURAS': np.float64(785514878.0273982),
 '9 - TÚNELES': np.float64(139518367.41477612),
 '10 - URBANISMO Y PAISAJISMO': None,
 '13 - CANTIDADES': None}

In [144]:
df_vp_fase_III.loc[:, ['CÓDIGO', 'LONGITUD KM', 'ALCANCE', '2.2 - TRAZADO Y DISEÑO GEOMÉTRICO']]

CÓDIGO  LONGITUD KM                    ALCANCE  \
0      0001       17.400            Segunda calzada   
1      0004       13.690                      Nuevo   
2      0005       10.000            Segunda calzada   
3      0005       14.300            Segunda calzada   
4      0005       10.200  operacion y mantenimiento   
5      0005        8.500  operacion y mantenimiento   
6      0005       13.500            Segunda calzada   
7      0005       47.200  operacion y mantenimiento   
8      0005        7.600            Segunda calzada   
9   0266702        5.000               Mejoramiento   
10  0300604        2.500            Segunda calzada   
11  0300605       17.000            Segunda calzada   
12  0321501       50.900               Mejoramiento   
13  0321501        9.000               Mejoramiento   
14  0321501       21.000               Mejoramiento   
15  0321501       14.000               Mejoramiento   
16  0321501        6.560               Mejoramiento   
17  0321501       18.920               Mejoramiento   
18  0321501       14.520               Mejoramiento   
19  0321501        9.860               Mejoramiento   
20  0347801        8.350             Rehabilitación   
21  0347801        8.600             Rehabilitación   
22  0347801        8.500             Rehabilitación   
23  0427901        5.000               Mejoramiento   
24  0552903       10.060               Mejoramiento   
25  0581301        5.243               Mejoramiento   
26  0654801       15.000             Rehabilitación   
27  0654801        3.120                      Nuevo   
28  0654801        3.370            Segunda calzada   
29  0654801        0.800              Construcción    
30  0654801        3.500            Segunda calzada   
31  0654801        5.170            Segunda calzada   
32  0654801       19.310             Puesta a punto   
33  0654801        8.210             Puesta a punto   
34  0654801        0.910            Segunda calzada   
35  0654801        3.160            Segunda calzada   
36  0654801       12.160             Puesta a punto   
37  0654801       12.160             Puesta a punto   
38  0654801        4.000            Segunda calzada   
39  0654801        2.000            Segunda calzada   
40  0654801        3.150             Rehabilitación   
41  0654801        1.850            Segunda calzada   
42  0654801        1.000             Puesta a punto   
43  0654801       14.000             Puesta a punto   
44  0654801       14.000             Puesta a punto   
45  0654801        7.840             Puesta a punto   
46  0654801        3.170            Segunda calzada   
47  0654801        2.000            Segunda calzada   
48  0654801        2.380            Segunda calzada   
49     6935       15.760            Segunda calzada   
50     6935       22.200            Segunda calzada   

    2.2 - TRAZADO Y DISEÑO GEOMÉTRICO  
0                        1.353405e+08  
1                        0.000000e+00  
2                        6.119988e+06  
3                        8.751583e+06  
4                        6.242388e+06  
5                        5.201990e+06  
6                        8.261984e+06  
7                        2.888634e+07  
8                        4.651191e+06  
9                        6.311029e+06  
10                       1.814013e+06  
11                       8.023420e+07  
12                       1.134648e+08  
13                       2.006255e+07  
14                       4.681261e+07  
15                       3.120841e+07  
16                       1.462337e+07  
17                       4.217593e+07  
18                       3.236758e+07  
19                       2.197963e+07  
20                       2.405652e+07  
21                       2.477678e+07  
22                       2.448867e+07  
23                       5.652966e+06  
24                       2.561191e+07  
25                       3.623384e+07  
26                       3.505602e+07  
27                      