In [136]:
import pandas as pd
import os
import sys
import warnings

warnings.filterwarnings('ignore')

project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.insert(0, project_root)

from app.services import ModelsManagement
from app.utils import ml_utils

from app.services.models_management import train_brindges_structures_model
from app.utils.ml_utils import get_bridges_structures_tunnels


%load_ext autoreload
%autoreload 2
%reload_ext autoreload


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [46]:
fase='III'
mm = ModelsManagement(fase)
df_vp = mm.prepare_data()
results, summary_df = mm.train_models()
summary_df

Target                    Alcance  \
0        2.1 - INFORMACIÓN GEOGRÁFICA            Segunda calzada   
1        2.1 - INFORMACIÓN GEOGRÁFICA  operacion y mantenimiento   
2        2.1 - INFORMACIÓN GEOGRÁFICA             Rehabilitación   
3   2.2 - TRAZADO Y DISEÑO GEOMÉTRICO            Segunda calzada   
4   2.2 - TRAZADO Y DISEÑO GEOMÉTRICO  operacion y mantenimiento   
5   2.2 - TRAZADO Y DISEÑO GEOMÉTRICO               Mejoramiento   
6   2.2 - TRAZADO Y DISEÑO GEOMÉTRICO             Rehabilitación   
7   2.2 - TRAZADO Y DISEÑO GEOMÉTRICO             Puesta a punto   
8                2.3 - SEGURIDAD VIAL            Segunda calzada   
9                2.3 - SEGURIDAD VIAL  operacion y mantenimiento   
10               2.3 - SEGURIDAD VIAL               Mejoramiento   
11               2.3 - SEGURIDAD VIAL             Rehabilitación   
12               2.3 - SEGURIDAD VIAL             Puesta a punto   
13        2.4 - SISTEMAS INTELIGENTES            Segunda calzada   
14        2.4 - SISTEMAS INTELIGENTES  operacion y mantenimiento   
15        2.4 - SISTEMAS INTELIGENTES               Mejoramiento   
16        2.4 - SISTEMAS INTELIGENTES             Puesta a punto   
17                        5 - TALUDES            Segunda calzada   
18                        5 - TALUDES               Mejoramiento   
19                        5 - TALUDES             Rehabilitación   
20                        5 - TALUDES             Puesta a punto   
21                      6 - PAVIMENTO            Segunda calzada   
22                      6 - PAVIMENTO             Rehabilitación   
23                      6 - PAVIMENTO               Mejoramiento   
24                      6 - PAVIMENTO             Puesta a punto   
25                     7 - SOCAVACIÓN            Segunda calzada   
26                     7 - SOCAVACIÓN  operacion y mantenimiento   
27                     7 - SOCAVACIÓN               Mejoramiento   
28                     7 - SOCAVACIÓN             Rehabilitación   
29                     7 - SOCAVACIÓN             Puesta a punto   
30                       11 - PREDIAL             Rehabilitación   
31       15 - OTROS - MANEJO DE REDES            Segunda calzada   
32       15 - OTROS - MANEJO DE REDES  operacion y mantenimiento   
33       15 - OTROS - MANEJO DE REDES             Puesta a punto   
34      16 - DIRECCIÓN Y COORDINACIÓN                    General   
35                       3 - GEOLOGÍA                    General   
36                         4 - SUELOS                    General   
37                    8 - ESTRUCTURAS                    General   
38                        9 - TÚNELES                    General   
39        10 - URBANISMO Y PAISAJISMO                    General   
40                    13 - CANTIDADES                    General   

                Model     R²           MAE          RMSE  MAPE (%)  n_samples  \
0          ElasticNet  1.000  4.525410e+02  4.795720e+02     0.033          4   
1          ElasticNet  1.000  3.358601e+03  3.565073e+03     0.163          3   
2          ElasticNet  1.000  6.105030e+02  7.056370e+02     0.002          3   
3                 SVR  0.492  9.999063e+05  1.874178e+06    29.641         16   
4          ElasticNet  1.000  1.542748e+04  1.637573e+04     0.163          3   
5               Ridge  0.338  4.954865e+06  9.490122e+06    36.907         10   
6          ElasticNet  1.000  1.599611e+05  1.849783e+05     1.210          5   
7          ElasticNet  1.000  1.080983e+04  1.358786e+04     0.169          8   
8    Gaussian Process  0.864  8.529342e+05  1.734885e+06    25.556         17   
9          ElasticNet  1.000  4.083710e+03  4.334749e+03     0.163          3   
10              Ridge  0.083  4.392731e+06  7.039014e+06    59.423         10   
11   Gaussian Process  0.900  1.427764e+06  3.036611e+06     4.501          5   
12         ElasticNet  1.000  1.162009e+04  1.460636e+04     0.169          8   
13     Bayesian Ridge  0.804  8.510775e+

In [137]:
predictions = mm.predict_fase_III(
    codigo='',
    longitud_km=8.35,
    puentes_vehiculares_und=10,
    puentes_vehiculares_m2=24258.85,
    puentes_peatonales_und=0,
    puentes_peatonales_m2=0,
    tuneles_und=5,
    tuneles_km=0.92,
    alcance='Rehabilitación',
    models=results
)
predictions

{'1 - TRANSPORTE': None,
 '2.1 - INFORMACIÓN GEOGRÁFICA': np.float64(38270337.10392039),
 '2.2 - TRAZADO Y DISEÑO GEOMÉTRICO': np.float64(24155713.73626182),
 '2.3 - SEGURIDAD VIAL': np.float64(18777320.907161202),
 '2.4 - SISTEMAS INTELIGENTES': None,
 '5 - TALUDES': np.float64(71829427.67336465),
 '6 - PAVIMENTO': np.float64(50552263.3647709),
 '7 - SOCAVACIÓN': np.float64(63413174.207543574),
 '11 - PREDIAL': np.float64(16639648.579338765),
 '12 - IMPACTO AMBIENTAL': None,
 '15 - OTROS - MANEJO DE REDES': None,
 '16 - DIRECCIÓN Y COORDINACIÓN': np.float64(194518014.8309798),
 '3 - GEOLOGÍA': np.float64(33210192.812050264),
 '4 - SUELOS': np.float64(137199890.22928584),
 '8 - ESTRUCTURAS': np.float64(581862872.6128875),
 '9 - TÚNELES': np.float64(103346938.82576008),
 '10 - URBANISMO Y PAISAJISMO': None,
 '13 - CANTIDADES': None}

In [132]:
fase='II'
mm_fase_II = ModelsManagement(fase)
df_vp_fase_II = mm_fase_II.prepare_data()
results_fase_II, summary_df_fase_II = mm_fase_II.train_models()
summary_df_fase_II

KeyboardInterrupt: 

In [130]:
target_suelos = '4 - SUELOS'
df_clean = df_vp[(df_vp[target_suelos] > 0) & (((df_vp['PUENTES VEHICULARES UND'] > 0) & (df_vp['PUENTES VEHICULARES M2'] > 0)) | (df_vp['PUENTES PEATONALES UND'] > 0))]

df_grouped = get_bridges_structures_tunnels(df_clean, target_suelos)
df_grouped

CÓDIGO          ALCANCE    4 - SUELOS  LONGITUD KM  \
0     0001  Segunda calzada  1.878437e+08       17.400   
1  0266702     Mejoramiento  1.326106e+07        5.000   
2  0300605  Segunda calzada  1.308015e+08       17.000   
3  0347801   Rehabilitación  5.740222e+08       16.850   
4  0552903     Mejoramiento  6.696069e+07       10.060   
5  0581301     Mejoramiento  4.285348e+07        5.243   
6  0654801            Nuevo  1.470113e+08       69.310   
7     6935  Segunda calzada  1.029912e+08       37.960   

   PUENTES VEHICULARES UND  PUENTES VEHICULARES M2  PUENTES PEATONALES UND  \
0                       11                    4856                      14   
1                        0                       0                       1   
2                       13                   16654                       0   
3                       26                   51069                       0   
4                        6                    3837                       0   
5                        2                      38                       0   
6                        7                       0                      10   
7                        4                    6292                       1   

   PUENTES PEATONALES M2  TUNELES UND  TUNELES KM  
0                   1365            0      0.0000  
1                     58            0      0.0000  
2                      0            0      0.0000  
3                      0           20      3.1947  
4                      0            0      0.0000  
5                      0            3      0.1460  
6                      0            1      0.0000  
7                     77            0      0.0000

In [131]:
predictors_suelos = ['PUENTES VEHICULARES UND', 'PUENTES VEHICULARES M2']
df_clean = ml_utils.remove_outliers(df_grouped, target_suelos)
ml_utils.train_multiple_models(df_clean, predictors_suelos, target_suelos, log_transform='both')
# train_brindges_structures_model(df_grouped, target_suelos, predictors_suelos, use_log_transform=True)

(array([[ 2.48490665,  8.48817624],
        [ 0.        ,  0.        ],
        [ 2.63905733,  9.72046575],
        [ 3.29583687, 10.84095252],
        [ 1.94591015,  8.25270668],
        [ 1.09861229,  3.66356165],
        [ 2.07944154,  0.        ],
        [ 1.60943791,  8.74719318]]),
 array([1.87843738e+08, 1.32610640e+07, 1.30801475e+08, 5.74022243e+08,
        6.69606925e+07, 4.28534818e+07, 1.47011320e+08, 1.02991160e+08]),
 array([1.76116199e+08, 1.41991054e+07, 2.34803427e+08, 3.36425760e+08,
        1.08196810e+08, 4.27960570e+07, 8.40274363e+07, 5.64600722e+07]),
 TransformedTargetRegressor(func=<ufunc 'log1p'>, inverse_func=<ufunc 'expm1'>,
                            regressor=Pipeline(steps=[('scaler',
                                                       StandardScaler()),
                                                      ('model',
                                                       Ridge(alpha=0.1))])),
 {'Model': 'Ridge',
  'R²': 0.659,
  'MAE': 63134066.208,


In [134]:
fase='III'
mm = ModelsManagement(fase)
df_vp = mm.prepare_data()
results, summary_df = mm.train_models()
summary_df

Target                    Alcance  \
0        2.1 - INFORMACIÓN GEOGRÁFICA            Segunda calzada   
1        2.1 - INFORMACIÓN GEOGRÁFICA  operacion y mantenimiento   
2        2.1 - INFORMACIÓN GEOGRÁFICA             Rehabilitación   
3   2.2 - TRAZADO Y DISEÑO GEOMÉTRICO            Segunda calzada   
4   2.2 - TRAZADO Y DISEÑO GEOMÉTRICO  operacion y mantenimiento   
5   2.2 - TRAZADO Y DISEÑO GEOMÉTRICO               Mejoramiento   
6   2.2 - TRAZADO Y DISEÑO GEOMÉTRICO             Rehabilitación   
7   2.2 - TRAZADO Y DISEÑO GEOMÉTRICO             Puesta a punto   
8                2.3 - SEGURIDAD VIAL            Segunda calzada   
9                2.3 - SEGURIDAD VIAL  operacion y mantenimiento   
10               2.3 - SEGURIDAD VIAL               Mejoramiento   
11               2.3 - SEGURIDAD VIAL             Rehabilitación   
12               2.3 - SEGURIDAD VIAL             Puesta a punto   
13        2.4 - SISTEMAS INTELIGENTES            Segunda calzada   
14        2.4 - SISTEMAS INTELIGENTES  operacion y mantenimiento   
15        2.4 - SISTEMAS INTELIGENTES               Mejoramiento   
16        2.4 - SISTEMAS INTELIGENTES             Puesta a punto   
17                        5 - TALUDES            Segunda calzada   
18                        5 - TALUDES               Mejoramiento   
19                        5 - TALUDES             Rehabilitación   
20                        5 - TALUDES             Puesta a punto   
21                      6 - PAVIMENTO            Segunda calzada   
22                      6 - PAVIMENTO             Rehabilitación   
23                      6 - PAVIMENTO               Mejoramiento   
24                      6 - PAVIMENTO             Puesta a punto   
25                     7 - SOCAVACIÓN            Segunda calzada   
26                     7 - SOCAVACIÓN  operacion y mantenimiento   
27                     7 - SOCAVACIÓN               Mejoramiento   
28                     7 - SOCAVACIÓN             Rehabilitación   
29                     7 - SOCAVACIÓN             Puesta a punto   
30                       11 - PREDIAL             Rehabilitación   
31       15 - OTROS - MANEJO DE REDES            Segunda calzada   
32       15 - OTROS - MANEJO DE REDES  operacion y mantenimiento   
33       15 - OTROS - MANEJO DE REDES             Puesta a punto   
34      16 - DIRECCIÓN Y COORDINACIÓN                    General   
35                       3 - GEOLOGÍA                    General   
36                         4 - SUELOS                    General   
37                    8 - ESTRUCTURAS                    General   
38                        9 - TÚNELES                    General   
39        10 - URBANISMO Y PAISAJISMO                    General   
40                    13 - CANTIDADES                    General   

                Model     R²           MAE          RMSE  MAPE (%)  n_samples  \
0          ElasticNet  1.000  4.525410e+02  4.795720e+02     0.033          4   
1          ElasticNet  1.000  3.358601e+03  3.565073e+03     0.163          3   
2          ElasticNet  1.000  6.105030e+02  7.056370e+02     0.002          3   
3                 SVR  0.492  9.999063e+05  1.874178e+06    29.641         16   
4          ElasticNet  1.000  1.542748e+04  1.637573e+04     0.163          3   
5               Ridge  0.338  4.954865e+06  9.490122e+06    36.907         10   
6          ElasticNet  1.000  1.599611e+05  1.849783e+05     1.210          5   
7          ElasticNet  1.000  1.080983e+04  1.358786e+04     0.169          8   
8    Gaussian Process  0.864  8.529342e+05  1.734885e+06    25.556         17   
9          ElasticNet  1.000  4.083710e+03  4.334749e+03     0.163          3   
10         ElasticNet  0.086  4.051322e+06  7.027524e+06    55.761         10   
11   Gaussian Process  0.900  1.427764e+06  3.036611e+06     4.501          5   
12         ElasticNet  1.000  1.162009e+04  1.460636e+04     0.169          8   
13     Bayesian Ridge  0.804  8.510775e+